---
title: "DDS_401_TeamNI_Case_Study_2"
author: "Michael J Wolfe & Ayoade Dare"
date: "February 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<center> <h1>Career Attrition Analysis for DDS Talent Management</h1> </center>
<center> <h1>NaturalIntelligence Analytics</h1> </center>

##Set up our environment and load the data
```{r 1}
library(randomForest)
library(RCurl)
library(ggplot2)
library(nnet)
library(kableExtra)
jobURL <- getURL("https://raw.githubusercontent.com/mjwolfe91/DDS_401_TeamNI_Case_Study2/master/Data/CaseStudy2-data.csv")
jobDF <- read.csv(text=jobURL, header=TRUE)
```
##Stratify some of the variables
```{r 2}
str(jobDF)
jobDF$AgeGroup <- cut(jobDF$X.U.FEFF.Age, c(-Inf, 18, 24, 34, 44, 54, 64, Inf))
levels(jobDF$AgeGroup) <- c("<18", "18-24", "25-34", "35-44", "45-54", "55-64", "65+")
```
##Not sure where to begin...so let's test them all!
```{r 3}
set.seed(71)
jobs.rf <- randomForest(Attrition ~ ., data=jobDF, importance=TRUE, proximity=TRUE)
print(jobs.rf)
```
##Now that it's done, let's see which ones are most important
```{r 4}
rf.dataframe <- data.frame(round(importance(jobs.rf),2))
kable(rf.dataframe, format = "html", align = "c") %>% kable_styling(bootstrap_options = c("striped", "hover"))
```
##Do MDS - 1 on proximity
```{r 5}
jobs.mds <- cmdscale(1 - jobs.rf$proximity, eig=TRUE)
op <- par(pty="s")
pairs(cbind(jobDF[,1:4], jobs.mds$points), cex=0.6, gap=0,
      col=c("red", "green", "blue")[as.numeric(jobDF$Attrition)],
      main="Job Attrition Data Predictors and MDS of Proximity Based on RandomForest")
par(op)
print(jobs.mds$GOF)
```
##Let's plot importance for each variable
```{r 6}
varImpPlot(jobs.rf)
importanceOrder <- order(-jobs.rf$importance)
names <- rownames(jobs.rf$importance)
for (name in names)
    partialPlot(jobs.rf, jobDF, eval(name), main=name, xlab=name)
```
##Now that we have the top 3, let's test the model!
```{r 7}
job.lm <- multinom(relevel(jobDF$Attrition, ref="Yes") ~ HourlyRate + StockOptionLevel + JobRole, data=jobDF)
summary(job.lm)
```